# -*- coding: utf-8 -*-
"""app_starbucks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzyFnMsBU2cjY1tf3jlvocUWN8qON-HQ
"""

import streamlit as st
import joblib
import numpy as np

# Load the default model
MODEL_PATH = "Starbucks_MLR (1).pkl"
model = joblib.load(MODEL_PATH)

# App title
st.title("Starbucks MLR Prediction Model")

# Input fields
amount_prepaid = st.number_input("Amount of Prepaid Card", min_value=0.0, format="%.2f")
age = st.number_input("Age", min_value=0, step=1)
days_per_month = st.number_input("Days per Month at Starbucks", min_value=0, step=1)
income = st.number_input("Income", min_value=0.0, format="%.2f")

# Prediction button
if st.button("Predict Cups of Coffee per Day"):
    # Prepare input data for prediction
    input_data = np.array([[amount_prepaid, age, days_per_month, income]])
    prediction = model.predict(input_data)[0]

    st.write(f"### Predicted Cups of Coffee per Day: {prediction:.2f}")

